language: python
os: linux
dist: trusty
sudo: required

matrix:
  include:
    # - python: 2.7
    # - python: 3.4
    # - python: 3.5
    - python: 3.6
    # - python: "3.6-dev"
    # - python: "nightly"

  # allow_failures:
    # - python: "3.6-dev"
    # - python: "nightly"

# whitelist
branches:
  only:
    - develop

# command to install dependencies
install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n py36 python=$TRAVIS_PYTHON_VERSION numpy pandas scipy gdal
  - source activate py36



# command to run tests
script: 
    # - export PYTHONPATH=$PYTHONPATH:.
    # - echo python path; python -c "from __future__ import print_function; import sys; print(sys.path)"
    - python -c "import os; is_travis = 'TRAVIS' in os.environ; print('TRAVIS {}'.format(is_travis))"
    - echo numpy version; python -c "import numpy; print(numpy.version.version)"
    - echo gdal version; python -c "from osgeo import gdal; print(gdal.__version__)"
    - python autotest/pt_stats.py
# after_success:
    # - coveralls